SET SCHEMA 'jagent';

INSERT INTO RQ_STATUSES (STATUS) VALUES 
	('NEW'),
	('IN_PROGRESS'),
	('PASS'),
	('FAILURE'),
	('ABORTED'),
	('KNOWN_ISSUES');


INSERT INTO JOBS (JOB_NAME, PROJECT_NAME) VALUES 
	('MFP-WEB-Default', 'qa');
